displayName=W2
author=Flxnts
description=Grand Exchange flips, live OSRS Wiki prices and automatic local trade tracking.
tags=grand exchange,ge,flipping,merching,prices,trades
version=
plugins=gg.w2.W2Plugin
build=standard
